[package]
name = "ui"
version = "0.0.1"
edition = "2021"
authors = [ "Abhinav Gunwant" ]

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", features = [ "lazy" ] }
dirs-next = "2.0.0"

